# Generated by Django 3.2.14 on 2022-07-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Pops',
            new_name='Pop',
        ),
    ]
